### ISSUE TITLE
四十大盗

### ISSUE THREAD

**Issue by xiaowei456** [LazyImmortal/Sesame#11]
### 程序版本 / 框架版本 / 模块版本

ONPTCH

### 系统版本 / Android版本

鸿蒙4.2

### 详细描述问题发生的具体原因

本地模式，还是显示四十大盗，和voitx也不兼容么？

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by LazyImmortal** [comment]
不支持ONPatch
