### ISSUE TITLE
视频刷红包或者领取消费抵扣小红包

### ISSUE THREAD

**Issue by 565183649** [LazyImmortal/Sesame#12]
### 增强类型

功能型增强

### 具体描述

希望可以多吃两个包子，作者辛苦

**Comment by berebrn** [comment]
> ### 增强类型
> 功能型增强
> 
> ### 具体描述
> 希望可以多吃两个包子，作者辛苦

脑子是个好东西，芝麻粒开发目标一点也不看。
现在大佬放宽了，源码也在这里，自己开发不就好了

**Comment by 565183649** [comment]
我还没学过……😥别骂了我学还不行么😭

**Comment by 565183649** [comment]
> > ### 增强类型
> > 功能型增强
> > ### 具体描述
> > 希望可以多吃两个包子，作者辛苦
> 
> 脑子是个好东西，芝麻粒开发目标一点也不看。 现在大佬放宽了，源码也在这里，自己开发不就好了

我还没学过……😥别骂了我学还不行么😭
