### ISSUE TITLE
商家开门/打卡失效

### ISSUE THREAD

**Issue by smile7pc** [LazyImmortal/Sesame#19]
### 程序版本 / 框架版本 / 模块版本

LSPatch 0.5.1 / 芝麻粒 v1.6.3

### 系统版本 / Android版本

miui 12.5.6 / android 11

### 详细描述问题发生的具体原因

商家开门/打卡失效，确认已经开启打卡开关

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by acooler15** [comment]
好像消费金任务出现了异常，导致后续任务不执行，把消费金签到关了试试

**Comment by acooler15** [comment]
错误日志也没有输出，好奇怪

**Comment by amulin202** [comment]
![Screenshot_2024-12-15-22-24-54-671_io.github.lazyimmortal.sesame-edit.jpg](https://github.com/user-attachments/assets/066d4fb4-ec32-452a-a9ca-c2629ce33c27)

消费金好像没毛病啊，我任务应该都有走。

**Comment by LazyImmortal** [comment]
> 错误日志也没有输出，好奇怪

错误日志只会在运行时遇到错误才会抛出。但是账号异常时的请求回应通常还是符合标准且能被芝麻粒正确处理的，或者你可以看看全部记录。BTW，我的开门打卡是正常的啊……

**Comment by acooler15** [comment]
> > 错误日志也没有输出，好奇怪
> 
> 错误日志只会在运行时遇到错误才会抛出。但是账号异常时的请求回应通常还是符合标准且能被芝麻粒正确处理的，或者你可以看看全部记录。BTW，我的开门打卡是正常的啊……

今天的任务正常执行了，查看runtime.log也能看到相关的请求相应
