### ISSUE TITLE
没有会员积分签到任务

### ISSUE THREAD

**Issue by zaq7434** [LazyImmortal/Sesame#22]
### 程序版本 / 框架版本 / 模块版本

lapatch

### 系统版本 / Android版本

12

### 详细描述问题发生的具体原因

以前的1.3版本在有如下任务。开关应该是设置->其他->领取积分

00:06:45 会员任务🎖️[滑动浏览15秒红包会场]#3积分
00:06:47 会员任务🎖️[逛年度好运拿红包]#3积分
00:06:48 会员任务🎖️[逛15秒精选超值好物]#3积分
00:06:50 会员任务🎖️[逛一逛蚂蚁新村]#3积分
00:06:52 会员任务🎖️[逛一逛滴滴出行小程序]#3积分

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)
无
</code></pre></details>

**Comment by LazyImmortal** [comment]
会员-会员签到包含任务
