### ISSUE TITLE
lapatch没法使用

### ISSUE THREAD

**Issue by tagaga** [LazyImmortal/Sesame#24]
### 程序版本 / 框架版本 / 模块版本

1.6.4.1

### 系统版本 / Android版本

华为鸿蒙4.3

### 详细描述问题发生的具体原因

启动显示芝麻关门 四十大盗 不支持的修补包，支付宝版本alipay10.6.50.8000，最新版本也试过，旧一点的版本也试过，就是不行，支付宝能启动，但是显示“芝麻关门 四十大盗 不支持的修补包”,芝麻粒的配置都可以保存，但是没有不起效

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by LazyImmortal** [comment]
不支持的修补包：内置模式

**Comment by tagaga** [comment]
采用的就是集成模式呀，必须改为本地模式？

**Comment by sheepeeing** [comment]
> 采用的就是集成模式呀，必须改为本地模式？

用本地模式。我用本地模式一直闪退，用回1.3.5内置版本了。
