### ISSUE TITLE
关于未ROOT手机使用LSPatch提示芝麻关门。

### ISSUE THREAD

**Issue by cat-sir** [LazyImmortal/Sesame#25]
### 程序版本 / 框架版本 / 模块版本

使用LSPatch 0.6 框架1.9.2 arm64-v8a 芝麻粒1.6.4.2

### 系统版本 / Android版本

OriginOS Android14

### 详细描述问题发生的具体原因

使用LSPatch提示芝麻关门，请问大佬，是不是不考虑LSPatch用户。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by amulin202** [comment]
早就支持了，还考不考虑。。。

**Comment by cat-sir** [comment]
> 早就支持了，还考不考虑。。。

大兄弟。怎么弄的，请教一下

**Comment by cat-sir** [comment]
> 早就支持了，还考不考虑。。。

收到，已解决问题谢谢大佬提示！
