### ISSUE TITLE
活力兑换🎐[神奇物种抽历史卡机会]#第1次

### ISSUE THREAD

**Issue by mztqgw** [LazyImmortal/Sesame#26]
### 程序版本 / 框架版本 / 模块版本

程序版本 ：10.6.70.8100)  LSPosed 1.9.2  模块版本 ：1.6.4.2

### 系统版本 / Android版本

12

### 详细描述问题发生的具体原因

没有选择活力值兑换 但每天都会自动执行一次兑换这个 换号了也是一样  神奇物种抽历史卡机会也没有勾选
活力兑换🎐[神奇物种抽历史卡机会]#第1次

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by LazyImmortal** [comment]
因为你历史物种没收集齐，并且勾选了自动收集历史物质的选项
![Screenshots](https://github.com/user-attachments/assets/3b21b185-5473-4bfc-8e19-1c962b18b3e0)
