### ISSUE TITLE
请授予支付宝读取芝麻粒的权限

### ISSUE THREAD

**Issue by Yangqs821** [LazyImmortal/Sesame#27]
### 程序版本 / 框架版本 / 模块版本

lsp1.0.11  模块1.6.4.2

### 系统版本 / Android版本

小米OS2A15

### 详细描述问题发生的具体原因

![Screenshot_2024-12-26-11-01-29-853_io github lazyimmortal sesame](https://github.com/user-attachments/assets/8b57998a-ca62-4189-aa43-7c8b34438993)

### 提供模块问题 Log 或必要 Log

39:36.397 RUNTIME: AppConfig, 初始APP配置
10:39:37.825 RUNTIME: FileUtil, [statistics]读:true;写:true
10:39:40.272 RUNTIME: 加载APP配置
10:39:40.299 RUNTIME: ConfigV2, 开始加载配置
10:39:40.300 RUNTIME: 加载配置: 默认
10:39:40.337 RUNTIME: ConfigV2, 格式化配置: 默认
10:39:40.340 RUNTIME: ConfigV2, 加载配置结束
10:40:03.669 RUNTIME: 保存配置: 默认
10:40:03.707 RUNTIME: FileUtil, [statistics]读:true;写:true
10:40:08.157 RUNTIME: ApplicationHook, Activity onResume
10:40:12.678 RUNTIME: ApplicationHook, hook matchVersion successfully
10:40:12.679 RUNTIME: ApplicationHook, hook login successfully
10:40:12.680 RUNTIME: ApplicationHook, hook service onCreate successfully
10:40:12.682 RUNTIME: ApplicationHook, hook MiscUtils successfully
10:40:12.682 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
10:40:13.225 RUNTIME: ApplicationHook, Service onCreate
10:40:13.426 RUNTIME: 请授予支付宝读取芝麻粒的权限
10:40:28.382 RUNTIME: ApplicationHook, hook matchVersion successfully
10:40:28.383 RUNTIME: ApplicationHook, hook login successfully
10:40:28.384 RUNTIME: ApplicationHook, hook service onCreate successfully
10:40:28.386 RUNTIME: ApplicationHook, hook MiscUtils successfully
10:40:28.386 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
10:40:28.727 RUNTIME: ApplicationHook, Activity onResume
10:40:28.837 RUNTIME: ApplicationHook, Service onCreate
10:40:28.899 RUNTIME: 请授予支付宝读取芝麻粒的权限
10:41:38.206 RUNTIME: ApplicationHook, Activity onResume
10:45:12.922 RUNTIME: ApplicationHook, hook matchVersion successfully
10:45:12.923 RUNTIME: ApplicationHook, hook login successfully
10:45:12.924 RUNTIME: ApplicationHook, hook service onCreate successfully
10:45:12.926 RUNTIME: ApplicationHook, hook MiscUtils successfully
10:45:12.926 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
10:45:13.366 RUNTIME: ApplicationHook, Service onCreate
10:45:14.059 RUNTIME: 请授予支付宝读取芝麻粒的权限
10:49:02.503 RUNTIME: ApplicationHook, hook matchVersion successfully
10:49:02.505 RUNTIME: ApplicationHook, hook login successfully
10:49:02.506 RUNTIME: ApplicationHook, hook service onCreate successfully
10:49:02.508 RUNTIME: ApplicationHook, hook MiscUtils successfully
10:49:02.508 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
10:49:03.064 RUNTIME: ApplicationHook, Activity onResume
10:49:03.257 RUNTIME: ApplicationHook, Service onCreate
10:49:03.414 RUNTIME: 请授予支付宝读取芝麻粒的权限
10:49:31.630 RUNTIME: ApplicationHook, hook matchVersion successfully
10:49:31.631 RUNTIME: ApplicationHook, hook login successfully
10:49:31.632 RUNTIME: ApplicationHook, hook service onCreate successfully
10:49:31.634 RUNTIME: ApplicationHook, hook MiscUtils successfully
10:49:31.634 RUNTIME: ApplicationHook, load success: com.eg.android.AlipayGphone
10:49:32.602 RUNTIME: ApplicationHook, Service onCreate
10:49:32.760 RUNTIME: 请授予支付宝读取芝麻粒的权限
10:50:25.138 RUNTIME: ApplicationHook, Activity onResume
10:51:50.343 RUNTIME: ApplicationHook, Activity onResume
10:54:13.772 RUNTIME: ApplicationHook, Activity onResume
10:54:52.511 RUNTIME: ApplicationHook, Activity onResume
10:54:52.740 RUNTIME: ApplicationHook, Activity onResume
10:55:10.302 RUNTIME: 加载APP配置
10:55:11.684 RUNTIME: FileUtil, [statistics]读:true;写:true
10:55:12.367 RUNTIME: 加载APP配置
11:00:13.014 RUNTIME: FileUtil, [statistics]读:true;写:true
11:00:15.403 RUNTIME: 加载APP配置
11:00:18.454 RUNTIME: FileUtil, [statistics]读:true;写:true
11:00:20.925 RUNTIME: 加载APP配置

**Comment by LazyImmortal** [comment]
隐藏应用列表使支付宝读取不到芝麻粒了
