### ISSUE TITLE
> > > 你没root吧

### ISSUE THREAD

**Issue by Abysslyz** [LazyImmortal/Sesame#29]
> > > 你没root吧
> > 
> > 
> > 要root才能用是吗
> 
> 不root用本地模式

lsp本地模式怎么操作
![Uploading Screenshot_20241224_163137.jpg…]()

_Originally posted by @tangjie602 in https://github.com/LazyImmortal/Sesame/discussions/10#discussioncomment-11656568_
本地模式一样无法使用，本地模式现在多了一个提示不可用的安装包。

**Comment by LazyImmortal** [comment]
这说明你安装了 X

**Comment by Abysslyz** [comment]
> 这说明你安装了 X

你说的是芝麻糊X？我主手机因为用不了你的芝麻粒，现在用的是芝麻糊X。为了试验我的备用手机只装你的芝麻粒还是一样的情况。
