### ISSUE TITLE
庄园优先领取任务奖励饲料

### ISSUE THREAD

**Issue by xzcgg** [LazyImmortal/Sesame#3]
### 增强类型

功能型增强

### 具体描述

大佬你好，现在是先收麦子，导致奖励饲料未领浪费了。

**Comment by kevinzhou9527** [comment]
别领麦子不就完了，自己手动操作一下，我奖励饲料都是手动领的

**Comment by hua-sky** [comment]
我也觉得任务执行顺序可以再优化一下.有些随时都能做的任务可以放后些,有时间的任务可以放前面执行.只是建议只是建议.

**Comment by LazyImmortal** [comment]
收麦子是一下子把所有的麦子全收了的，越晚收积累的越多，浪费越严重，所以不考虑优先领饲料。你可以关闭收麦子功能，自主控制时间手动收取麦子。

**Comment by xzcgg** [comment]
> 收麦子是一下子把所有的麦子全收了的，越晚收积累的越多，浪费越严重，所以不考虑优先领饲料。你可以关闭收麦子功能，自主控制时间手动收取麦子。

好的，感谢大佬
