### ISSUE TITLE
蚂蚁庄园不能自动雇佣的BUG

### ISSUE THREAD

**Issue by Arthasphq** [LazyImmortal/Sesame#30]
### 程序版本 / 框架版本 / 模块版本

10.6.66 google play版支付宝；LSPOSED 1.9.2；芝麻粒V1.6.4.2

### 系统版本 / Android版本

Android 10

### 详细描述问题发生的具体原因

庄园使用亲情卡收养两个好友的小鸡，在已经设置雇佣｜动作为“雇佣已选好友”的情况下，设置雇佣｜好友列表为２个已收养好友

雇佣８小时结束后，芝麻粒无法自动雇佣两只小鸡，只能每次８小时结束后手动雇佣

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

LOG文件太大，无法顺利粘贴出来，反正这个功能不能正常运行

</code></pre></details>

**Comment by LazyImmortal** [comment]
亲情卡的蹭吃是无限期的，应该是你好友把小鸡召唤回去了。在程序检测周期内，小鸡在吃饲料自然也就不会雇佣了。

**Comment by Arthasphq** [comment]
> 亲情卡的蹭吃是无限期的，应该是你好友把小鸡召唤回去了。在程序检测周期内，小鸡在吃饲料自然也就不会雇佣了。

不是的，我雇佣的两个好友基本不玩这个，我已经收养几个月了，他们从未召回过

**Comment by LazyImmortal** [comment]
> > 亲情卡的蹭吃是无限期的，应该是你好友把小鸡召唤回去了。在程序检测周期内，小鸡在吃饲料自然也就不会雇佣了。
> 
> 不是的，我雇佣的两个好友基本不玩这个，我已经收养几个月了，他们从未召回过

亲情卡雇佣的小鸡，不召回是会一直呆在你庄园的。

**Comment by Arthasphq** [comment]
> > > 亲情卡的蹭吃是无限期的，应该是你好友把小鸡召唤回去了。在程序检测周期内，小鸡在吃饲料自然也就不会雇佣了。
> > 
> > 
> > 不是的，我雇佣的两个好友基本不玩这个，我已经收养几个月了，他们从未召回过
> 
> 亲情卡雇佣的小鸡，不召回是会一直呆在你庄园的。

是一直呆在我庄园，但是不能用芝麻粒实现到期自动连续雇佣，然后就拿不到收养的两只小鸡产生的肥料了。

**Comment by LazyImmortal** [comment]
> > > > 亲情卡的蹭吃是无限期的，应该是你好友把小鸡召唤回去了。在程序检测周期内，小鸡在吃饲料自然也就不会雇佣了。
> > > 
> > > 
> > > 不是的，我雇佣的两个好友基本不玩这个，我已经收养几个月了，他们从未召回过
> > 
> > 
> > 亲情卡雇佣的小鸡，不召回是会一直呆在你庄园的。
> 
> 是一直呆在我庄园，但是不能用芝麻粒实现到期自动连续雇佣，然后就拿不到收养的两只小鸡产生的肥料了。

你既然想要肥料，那么你为什么要用亲情卡呢……

**Comment by Arthasphq** [comment]
> > > > > 亲情卡的蹭吃是无限期的，应该是你好友把小鸡召唤回去了。在程序检测周期内，小鸡在吃饲料自然也就不会雇佣了。
> > > > 
> > > > 
> > > > 不是的，我雇佣的两个好友基本不玩这个，我已经收养几个月了，他们从未召回过
> > > 
> > > 
> > > 亲情卡雇佣的小鸡，不召回是会一直呆在你庄园的。
> > 
> > 
> > 是一直呆在我庄园，但是不能用芝麻粒实现到期自动连续雇佣，然后就拿不到收养的两只小鸡产生的肥料了。
> 
> 你既然想要肥料，那么你为什么要用亲情卡呢……

使用了亲情卡，收养的小鸡吃的饲料产生的蛋也是我的。雇佣小鸡之后，产生的肥料也归我。两者不矛盾啊，我既想要蛋，又想要肥料，😄
最重要的原因是，庄园每天领到的饲料太多了，压根消耗不完，要把这些饲料价值最大化

**Comment by LazyImmortal** [comment]
> > > > > > 亲情卡的蹭吃是无限期的，应该是你好友把小鸡召唤回去了。在程序检测周期内，小鸡在吃饲料自然也就不会雇佣了。
> > > > > 
> > > > > 
> > > > > 不是的，我雇佣的两个好友基本不玩这个，我已经收养几个月了，他们从未召回过
> > > > 
> > > > 
> > > > 亲情卡雇佣的小鸡，不召回是会一直呆在你庄园的。
> > > 
> > > 
> > > 是一直呆在我庄园，但是不能用芝麻粒实现到期自动连续雇佣，然后就拿不到收养的两只小鸡产生的肥料了。
> > 
> > 
> > 你既然想要肥料，那么你为什么要用亲情卡呢……
> 
> 使用了亲情卡，收养的小鸡吃的饲料产生的蛋也是我的。雇佣小鸡之后，产生的肥料也归我。两者不矛盾啊，我既想要蛋，又想要肥料，😄 最重要的原因是，庄园每天领到的饲料太多了，压根消耗不完，要把这些饲料价值最大化

你应该去蚂蚁集团改机制，而不是给我提 issue。
