### ISSUE TITLE
关于绿色经营执行时间优化

### ISSUE THREAD

**Issue by DonkeyKong9527** [LazyImmortal/Sesame#4]
### 增强类型

功能型增强

### 具体描述

![Screenshot_2024-07-25-00-15-45-425_io github lazyimmortal sesame-edit](https://github.com/user-attachments/assets/8491017f-dc26-41fa-bf6c-92dfb14d4188)
大佬，绿色经营，能否更改执行时间呢，我发现，0000-0700之间执行容易失败频繁弹vpn，而且好友金币是早上七点左右才有，早上执行任务弹vpn没那么频繁

**Comment by mahakalaya** [comment]
合种没成功过

**Comment by baby1128** [comment]
> 合种没成功过

另外开issues报情况。
